In [3]:
import numpy as np

# 통계를 위한 연산

In [6]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [7]:
# 합과 (산술)평균 :sum() , mean()
[arr1.sum(),arr1.mean()]


[10, 2.0]

In [9]:
# 표준편차와 분산: 얼마나 데이터들이 떨어져있는지 확인  : std()  ,    var()
[arr1.std() , arr1.var()]

[1.4142135623730951, 2.0]

In [11]:
# 최소값과 최대값 max(),  min()
[arr1.max() , arr1.min()]

[4, 0]

In [13]:
# 누적합과 누적곱 : cumsum(), cumprod()
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [14]:
# 누적합
arr2.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [15]:
# 누적곱
arr2.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

# 행렬 연산
* 행렬곱     
    * a.dot(B) or np.dot(a,b)
*전치행렬    
    * a.transpose() or np.transpose(a)
*역행렬       
    * np.linalg.inv(a)
*행렬식      
    * np.linalg.det(a)


In [18]:
A = np.arange(1,5).reshape(2,2)
# np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [20]:
B = np.array([3,2,0,1]).reshape(2,2)
B


array([[3, 2],
       [0, 1]])

## 행렬의 곱

In [22]:
# 행렬곱
np.dot(A,B)

array([[ 3,  4],
       [ 9, 10]])

In [23]:
A.dot(B)

array([[ 3,  4],
       [ 9, 10]])

## 전치행렬

In [24]:
# 전치행렬
A.transpose()

array([[1, 3],
       [2, 4]])

In [25]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

## 역행렬

In [27]:
# 역행렬(inverse)
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
# 행렬식 (determinant)
np.linalg.det(A)

-2.0000000000000004

In [29]:
# 행렬 A * inv(A) = 단위행렬이 나옴
np.dot(A, np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

# array 인덱싱과 슬라이싱
* 인덱싱 : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는것
* 슬라이싱 : 범위를 지정해 배열의 원소를 선택하는 것

## 1차원 배열의 인엑싱
### 배열명[위치]
* 파이썬의 인덱싱과 동일
* 0번째로 시작함

In [31]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 0번째 요소
arr1[0]

0

In [33]:
# 3번째 요소
arr1[2]

2

배열명.[[위치,위치2,위치n]]

In [1]:
# 1,2,3,4, 위치 :shape -> (m,n,p)  => 3차원
# 대괄호[] 인덱스 지정은 [m] -> 1차원 [m,n] -> 2차원 [m,n,p] -> 3차원
# 여러 인덱스 요소를 지정 : 리스트로 주어야한다
# arr1[1,2,3]  -> 3차원
arr1[[1,3,4]]  #  -> 이거느 ㄴ돼는거임

NameError: name 'arr1' is not defined

## 2차원의 인덱싱

In [36]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# 2차원의 array에서 인덱싱을 하기 위해서 2개의 인자를 입력해야한다
# arr2[3,2] 안됨 0,1,2 라서
arr2[2,3]

12

In [39]:
# 0행 0열 값 변경
arr2[0,0] = 90
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 2차원배열명[행위치]
* 2차원 배열에서 지정한 행 전체가 선택됨

In [41]:
# 두번째 행(1행) 선택
arr2[1]

array([5, 6, 7, 8])

### 2차원배열명[:,열위치]
* 2차원 배열에서 열전체

In [50]:
# 1열을 선택 :
arr2[:,1]

array([ 2,  6, 10])

In [57]:
# 두번째 행 변경
arr2[1] = np.array([-5,1,10,9])   # 행의 크기가 같아야함
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

### 배열명[[행위치1,....행위치n],[열위치1,...열위치n]]

In [53]:
arr2[[0,2],[0,1]]  # 대각선 인듯의 원소 가져옴

array([90, 10])

## 배열명[조건]

In [54]:
# 10이상만 선택
arr2 > 10

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [55]:
# 비교연산 결과를 인덱스로 지정
arr2[arr2 > 10]

array([90, 11, 12])

In [62]:
# 짝수는 원소 선택
arr2[arr2 % 2 ==0]

array([90,  2,  4, 10, 10, 12])

# 1차원 배열의 슬라이스(Slicing)
## 배열[시작위치:끝위치]
### : 시작위치에서 끝위치-1 에 해당하는 배열의 원소를 반환

In [63]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# 3번째 요소부터 8번째
arr1[3:9]   # ':'콜론으로 범위지정  

array([3, 4, 5, 6, 7, 8])

In [69]:
# 배열명[start:end+1::step]  start에서 end 범위까지의 자료중 step간격으로 인덱싱 
arr1[3:9:2]  # 3번째에서 9번째 에 2칸씩 

array([3, 5, 7])

In [70]:
arr1[:9:2] # 처음부터 8까지 2씩 인덱싱

array([0, 2, 4, 6, 8])

In [73]:
arr1[3::2]  # 3부터 끝까지 2칸씩

array([3, 5, 7, 9])

In [75]:
arr1[::3] # all 3씩 슬라

array([0, 3, 6, 9])

In [76]:
arr1[::-1]  # 거꾸로 출력

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [77]:
arr1[::-2]  # 거꾸로 -2씩

array([9, 7, 5, 3, 1])

## 배열[:끝]   처음부터 끝위치-1 까지 반환

In [78]:
arr1[:3]

array([0, 1, 2])

## 배열[시작위치:]

In [79]:
arr1[5:]

array([5, 6, 7, 8, 9])

In [81]:
arr1[:]   # 모든 위치

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2차원 배열  인덱싱

In [82]:
arr2

array([[90,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

In [83]:
# 2행 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [84]:
arr2[2]

array([ 9, 10, 11, 12])

In [85]:
# 모든 열으 ㅣ3번째 요소 꺼내기
arr2[:,2]

array([ 4,  9, 12])

In [87]:
# 1~2행 1~2열 요소 
arr2[1:3,1:3]

array([[ 1, 10],
       [10, 11]])

## 특정행 선택 후 열 슬라이싱 배열[행위치][열시작:열끝]

In [89]:
arr3 = np.arange(10,100,10).reshape(3,3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [92]:
# 1행의 0열과 1열 요소선택
# arr3[1,:2]
arr3[1][:2]

array([40, 50])

In [93]:
# 참고 인덱싱의 예
arr3[2][1]

80

In [100]:
# 0~1행 1~2열의 요소변경
arr3[0:2,1:3] = np.array([[1,3],[4,1]])
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])

# array boolean 인덱싱(mask)
* 다차원의 인덱싱을 응용하여 boolean인덱싱
* boolean인덱싱을 통해 만들어냉 array를 통해 원하는 행또는 열의 값만 뽑아냄
* 가리고싶은 부분은 가리고,원하는 요소만 꺼냄

In [102]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
names

array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [103]:
# names 크기확인
names.shape

(8,)

In [106]:
# 8행 4열의 실수 난수 배열 생성
data = np.random.randn(8,4)   # randn 실수 난수 ?????????
data

array([[-1.08615578, -1.38942812,  1.86804066,  1.19335062],
       [ 0.25198122, -0.01533798, -0.84859451, -0.573424  ],
       [ 0.40160011, -2.55879215, -0.08957113, -1.61205825],
       [ 0.66375651,  1.587772  ,  0.91801621,  0.20487275],
       [-0.67748865,  0.36328161,  0.09043518, -0.8346159 ],
       [-0.19348487,  1.74380184, -0.4036438 ,  0.69872378],
       [-0.80000883, -0.09898927, -0.16829716, -1.40678057],
       [ 0.80208752,  1.36957481, -2.04690295,  1.6700336 ]])

In [107]:
data.shape

(8, 4)

In [109]:
# 요소가 Beomwoo 인 항목에 대한 mask 생성
names_mask = (names == 'Beomwoo')
names_mask

array([ True,  True, False, False, False,  True, False,  True])

In [114]:
# 요소가 Beomwoo 인 항목에 위치와 같은 행의 자료 가져오기
# data[names_mask,:]   # True에 해당하는 것만 가져옴  아래와 결과는 같아
data[names_mask] 

array([[-1.08615578, -1.38942812,  1.86804066,  1.19335062],
       [ 0.25198122, -0.01533798, -0.84859451, -0.573424  ],
       [-0.19348487,  1.74380184, -0.4036438 ,  0.69872378],
       [ 0.80208752,  1.36957481, -2.04690295,  1.6700336 ]])

In [116]:
# 요소가 kim인 행의 데이터만 꺼내기
# names_mask_kim = (names == 'Kim')
# data[names_mask_kim]
# data[names=='Kim']
data[names=='Kim',:]

array([[ 0.40160011, -2.55879215, -0.08957113, -1.61205825]])

In [120]:
# 논리 연산을 응용하여 , 요소가 kim 또는 park인 행의 데이터만 꺼내기
# names_mask_kp = (names == 'kim' or names == 'Park')
# data[names_mask_kp]
data[(names == 'Kim') | (names == 'Park'),:]

array([[ 0.40160011, -2.55879215, -0.08957113, -1.61205825],
       [-0.80000883, -0.09898927, -0.16829716, -1.40678057]])

## 0번째 열이 0보다 작은행

In [122]:
data[:,0] < 0

array([ True, False, False, False,  True,  True,  True, False])

In [123]:
# 생성도니 마스크로 0번째 열의 값이 0보다 작은 행을 구함
data[data[:,0]<0]  # 행만쭉 가져옴

array([[-1.08615578, -1.38942812,  1.86804066,  1.19335062],
       [-0.67748865,  0.36328161,  0.09043518, -0.8346159 ],
       [-0.19348487,  1.74380184, -0.4036438 ,  0.69872378],
       [-0.80000883, -0.09898927, -0.16829716, -1.40678057]])

* 0번째 열이 0보다 작은 행의 2,3번째 열 데이터 가져오기

In [128]:
data[data[:,0] < 0][:,2:4]
data[data[:,0]<0,2:4]

array([[ 1.86804066,  1.19335062],
       [ 0.09043518, -0.8346159 ],
       [-0.4036438 ,  0.69872378],
       [-0.16829716, -1.40678057]])

# array에 적용되는 다양한 함수

In [131]:
# 5행 3열의 실수난수 배열 생성
np.random.randn(5,3)

array([[ 0.4030212 , -0.87450267,  0.92345977],
       [-1.38161372, -0.84227701,  2.34481184],
       [-1.2627782 ,  0.09745509, -0.93638859],
       [ 0.33374251, -0.24076858,  1.10362517],
       [ 0.41930848,  1.82302625, -1.54614854]])

## 수학 관련 함수
* 제곰급,절대값 ,삼각,지수로그,반올림함수 등등


In [132]:
# 각성분의 절대값 계산
data = np.random.randn(5,3)
np.abs(data)

array([[0.72210832, 1.82737755, 1.11438604],
       [0.18720547, 1.86799541, 1.29646688],
       [1.75223407, 1.20086173, 0.7472144 ],
       [1.64888349, 0.01319665, 0.64972718],
       [0.30660951, 0.16044283, 1.3227811 ]])

* 수학 함수  https://numpy.org/doc/stable/reference/routines.math.html
* 랜덤 함수 관련 https://numpy.org/doc/stable/reference/random/legacy.html
* 통계를 위한 함수 https://numpy.org/doc/stable/reference/routines.statistics.html


In [133]:
# 각 성분의 제곱근 (== data**0.5) 가능 잘안됨
np.sqrt(data)

<ipython-input-133-67f3faf92c7c>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([[0.84976957, 1.35180529, 1.05564485],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan, 0.40055316,        nan]])

* 지수함수

In [134]:
# 각 성분을 무리수e의 지수로 삼은 값을 계산하기  e^x
np.exp(data)

array([[2.05876918, 6.21756001, 3.04769645],
       [0.82927333, 0.15443293, 0.27349638],
       [0.17338615, 0.30093478, 0.47368421],
       [0.19226445, 0.98689004, 0.52218822],
       [0.73593792, 1.17403066, 0.2663934 ]])

**로그함수**
* 자연로그 log()
* 상용로그  log10()
* 밑이2인로그 log2()

In [135]:
# 자연로그
np.log(abs(data))

array([[-0.32558012,  0.60288191,  0.10830362],
       [-1.67554852,  0.62486588,  0.25964278],
       [ 0.56089159,  0.1830394 , -0.29140312],
       [ 0.50009839, -4.32779234, -0.43120272],
       [-1.18218029, -1.82981757,  0.27973641]])

In [136]:
# 상용로그
np.log10(abs(data))

array([[-0.14139765,  0.26182828,  0.04703566],
       [-0.72768148,  0.2713758 ,  0.11276143],
       [ 0.24359212,  0.079493  , -0.12655477],
       [ 0.21718997, -1.87953633, -0.18726896],
       [-0.51341438, -0.79467967,  0.12148798]])

In [137]:
# 밑이2인 로그
np.log2(abs(data))

array([[-0.46971283,  0.86977473,  0.1562491 ],
       [-2.41730554,  0.90149091,  0.37458535],
       [ 0.80919551,  0.26407004, -0.42040584],
       [ 0.72148946, -6.24368454, -0.62209403],
       [-1.70552564, -2.63986873,  0.40357434]])

## 반올림함수

In [138]:
data

array([[ 0.72210832,  1.82737755,  1.11438604],
       [-0.18720547, -1.86799541, -1.29646688],
       [-1.75223407, -1.20086173, -0.7472144 ],
       [-1.64888349, -0.01319665, -0.64972718],
       [-0.30660951,  0.16044283, -1.3227811 ]])

In [139]:
# 각 성분의 소수 첫 자리 내림
np.floor(data)

array([[ 0.,  1.,  1.],
       [-1., -2., -2.],
       [-2., -2., -1.],
       [-2., -1., -1.],
       [-1.,  0., -2.]])

## NaN 여부확인

In [140]:
# 각 성분이 nan인 경우 True를 아닌경우 False를 반환하기
np.isnan(data)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [143]:
# 로그변환한 배열중 nan 확인
np.isnan(np.log(data))

<ipython-input-143-2fd9a5d30609>:2: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(data))


array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

## 무한대 (inf) 확인

In [ ]:
# 각 성분이 무한대인 경우


## 삼각함수

In [145]:
#cos
np.cos(data)

array([[ 0.75041386, -0.25377518,  0.44072868],
       [ 0.98252817, -0.29284323,  0.27090152],
       [-0.18044391,  0.36155446,  0.7335848 ],
       [-0.07800783,  0.99991293,  0.79624887],
       [ 0.95336239,  0.98715663,  0.2454804 ]])

In [146]:
np.sin(data)

array([[ 0.66096825,  0.96726323,  0.89764037],
       [-0.18611392, -0.95616047, -0.96260707],
       [-0.98358528, -0.93235099, -0.67959792],
       [-0.99695275, -0.01319627, -0.6049692 ],
       [-0.30182801,  0.15975537, -0.96940155]])

In [147]:
np.tan(data)

array([[ 0.88080496, -3.81149654,  2.03671876],
       [-0.18942349,  3.2650933 , -3.55334686],
       [ 5.45091992, -2.57872907, -0.92640676],
       [12.78016265, -0.01319742, -0.75977401],
       [-0.31659316,  0.16183386, -3.94899775]])

## sum,productsmdifferences

In [148]:
data

array([[ 0.72210832,  1.82737755,  1.11438604],
       [-0.18720547, -1.86799541, -1.29646688],
       [-1.75223407, -1.20086173, -0.7472144 ],
       [-1.64888349, -0.01319665, -0.64972718],
       [-0.30660951,  0.16044283, -1.3227811 ]])

In [150]:
# 전체 성분 계산
np.sum(data)

-7.168861131561547

In [151]:
# 열간의 합을 계산
# 같은 열 이나 합의 요소들을 합한 결과
# axis 는 같은열 axis = 0 열의 합 axis = 1 행의 합
np.sum(data,axis=1)

array([ 3.66387191, -3.35166775, -3.7003102 , -2.31180732, -1.46894778])

In [152]:
np.sum(data,axis=0)

array([-3.17282422, -1.0942334 , -2.90180351])

In [154]:
# 전체 성분의 평균
np.mean(data)

-0.4779240754374365

In [156]:
# 행별 평균 계산
np.mean(data,axis=1)
# 열별 평균
np.mean(data,axis=0)

array([-0.63456484, -0.21884668, -0.5803607 ])

In [157]:
# 전체 성분의 표준편차 계산
np.std(data)
# 전체의 열
np.std(data,axis=0)
# 전체의 행 표준편차
np.std(data,axis=1)

array([0.45751245, 0.69778702, 0.41094362, 0.67321417, 0.61920162])

In [158]:
# 열방향에서 최소값 
np.min(data,axis =0)

array([-1.75223407, -1.86799541, -1.3227811 ])

**최대값 최소값 위치 인덱스 argmax(),argmin()***

In [159]:
data

array([[ 0.72210832,  1.82737755,  1.11438604],
       [-0.18720547, -1.86799541, -1.29646688],
       [-1.75223407, -1.20086173, -0.7472144 ],
       [-1.64888349, -0.01319665, -0.64972718],
       [-0.30660951,  0.16044283, -1.3227811 ]])

In [167]:
# 전체 성분의 최소값 , 최대값이 위치한 인덱스를 반환
[np.argmax(data),np.argmin(data)]  # 전체 에서 가장 큰데이터의 위치
# [np.max(data),np.argmin(data)]

[1, 4]

In [168]:
# 행방향으로 최대값이 위치한 인덱스 반환
np.argmax(data,axis=1)

array([1, 0, 2, 1, 1], dtype=int64)

### 누적합 cumsum 누적곱 cumprod

In [169]:
# 맨처음 성분부터 각 성분까지의 누적ㅎ삽 또ㅓ는 누적곱 계산
np.cumsum(data)

array([ 0.72210832,  2.54948587,  3.66387191,  3.47666645,  1.60867104,
        0.31220416, -1.44002991, -2.64089164, -3.38810603, -5.03698952,
       -5.05018617, -5.69991335, -6.00652287, -5.84608003, -7.16886113])

In [170]:
# 열기분 누적합
np.cumsum(data,axis=0)

array([[ 0.72210832,  1.82737755,  1.11438604],
       [ 0.53490286, -0.04061786, -0.18208083],
       [-1.21733122, -1.24147959, -0.92929523],
       [-2.86621471, -1.25467623, -1.57902241],
       [-3.17282422, -1.0942334 , -2.90180351]])

In [171]:
# 누적곱
np.cumprod(data)

array([ 7.22108321e-01,  1.31956453e+00,  1.47050430e+00, -2.75286442e-01,
        5.14233809e-01, -6.66687101e-01,  1.16819185e+00, -1.40283689e+00,
        1.04821992e+00, -1.72839252e+00,  2.28089896e-02, -1.48196205e-02,
        4.54383661e-03,  7.29026028e-04, -9.64341851e-04])

In [172]:
np.cumprod(data,axis=1)

array([[ 0.72210832,  1.31956453,  1.4705043 ],
       [-0.18720547,  0.34969895, -0.45337311],
       [-1.75223407,  2.10419083, -1.57228168],
       [-1.64888349,  0.02175974, -0.01413789],
       [-0.30660951, -0.0491933 ,  0.06507197]])

In [173]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(data)

array([[ 0.72210832,  1.11438604,  1.82737755],
       [-1.86799541, -1.29646688, -0.18720547],
       [-1.75223407, -1.20086173, -0.7472144 ],
       [-1.64888349, -0.64972718, -0.01319665],
       [-1.3227811 , -0.30660951,  0.16044283]])

sord(data,axis,order = None)

에서 order를 이용해서 내림차순 가능

In [174]:
# 전체 성분에 대해서 내림차순으로 정렬 [::-1] 를적용 : 마지막 행부터 정렬
np.sort(data)[::-1]   

array([[-1.3227811 , -0.30660951,  0.16044283],
       [-1.64888349, -0.64972718, -0.01319665],
       [-1.75223407, -1.20086173, -0.7472144 ],
       [-1.86799541, -1.29646688, -0.18720547],
       [ 0.72210832,  1.11438604,  1.82737755]])

In [176]:
# 열방향으로 오름차순 정렬
np.sort(data,axis = 0)

array([[-1.75223407, -1.86799541, -1.3227811 ],
       [-1.64888349, -1.20086173, -1.29646688],
       [-0.30660951, -0.01319665, -0.7472144 ],
       [-0.18720547,  0.16044283, -0.64972718],
       [ 0.72210832,  1.82737755,  1.11438604]])

## 2개의 array에 적용되는함수


In [180]:
data1 =  np.random.randn(5,3)
data2 = np.random.rand(5,3)

***두개의 array에 대해 동일한 위치성분끼리 연산***

In [181]:
# 두 배열의 함
np.add(data1,data2)

array([[ 1.44321694,  0.44588261,  0.78447551],
       [ 2.77778452, -0.68120822,  1.08999819],
       [ 0.32485193,  0.61785969,  0.76193341],
       [ 0.65575066, -0.53959853,  0.10831973],
       [-0.28621727,  0.06702751,  1.61880744]])

In [183]:
# 두배열의 차
np.subtract(data1,data2)

array([[ 1.22878695, -0.52555953, -0.53997839],
       [ 2.16242166, -2.619578  , -0.00912669],
       [-0.5096754 ,  0.18803567, -0.35070146],
       [ 0.58492048, -1.14195271, -1.19070957],
       [-0.64510077, -1.06993765,  0.47813651]])

In [184]:
# 두배열의 곱
np.multiply(data1,data2)

array([[ 0.14323944, -0.01935038,  0.08095629],
       [ 0.76000486, -1.59953606,  0.29700319],
       [-0.03856006,  0.0865983 ,  0.11438775],
       [ 0.02196924, -0.25322236, -0.35151403],
       [-0.08355867, -0.28506847,  0.59798075]])

In [185]:
# 두배열의 나누기
np.divide(data1,data2)

array([[12.46096185, -0.08201922,  0.18460221],
       [ 8.02811876, -1.70286715,  0.9833928 ],
       [-0.22147084,  1.87494257,  0.36960189],
       [17.51613647, -2.79163205, -0.83322974],
       [-2.59504275, -0.882094  ,  1.83834259]])

* 최대값 또는 최소값

In [186]:
# 두개의 array에 대해 동일한 위치의 성분끼리 비교
# 최대 혹은 최소값
np.maximum(data1,data2)

array([[1.33600194, 0.48572107, 0.66222695],
       [2.47010309, 0.96918489, 0.54956244],
       [0.41726366, 0.40294768, 0.55631743],
       [0.62033557, 0.30117709, 0.64951465],
       [0.17944175, 0.56848258, 1.04847197]])

In [187]:
np.minimum(data1,data2)

array([[ 0.10721499, -0.03983846,  0.12224856],
       [ 0.30768143, -1.65039311,  0.54043575],
       [-0.09241174,  0.21491201,  0.20561598],
       [ 0.03541509, -0.84077562, -0.54119492],
       [-0.46565902, -0.50145507,  0.57033546]])

***numpy는 수치계산을 위해 사용한다***