***판다스의 목적***
* 서로 다른 유형으 ㅣ데이터를 공통도니 포맷으로 정리하는것
* 행과 열로 이루어진 2차우너 데이터 프레임을 처리 할 수있는 함수제공
* 실무사용 형태: 데이터 프레임

In [18]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'1.2.4'

# pandas 의 데이터구조 
    1. series 데이터   -> 1차원?
    2. 데이터 프레임    -> 2차원?
    
https://www.kdnuggets.com/2017/01/pandas-cheat-sheet.html


# series 데이터
* pandas의 기본 객체 중 하나
* numpy의 ndarray를 기반으로 인덱싱 기능 추가 1차원 배열 나타냄
* index 지정 하지 않을시 기본적으로 ndarry와 같이 기본 인덱스를 0으로 함 지정시 지정값
* 같은 타입의 0개 이상의 데이터를 가질수있음 

* 시리즈 생성은 Series() 이용 

Series 생성

pd.Series(deq_data) 함수이용
* deq_data : 리시트,딕셔너리 ,튜플 데이터 타입
* 인덱스는 기본적으로 0으로 자동생성

In [6]:
s = pd.Series([1,2,3,])
s
# 왼쪽이 인덱스 가 되고 오른쪽이 값 파이썬의 em머시기와 비슷함

0    1
1    2
2    3
dtype: int64

In [10]:
s1 = pd.Series(range(10,60,10))
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [12]:
# 문자열을 리스트로 시리즈
s2 = pd.Series(['A','B','C'])
s2

0    A
1    B
2    C
dtype: object

In [13]:
s2 = pd.Series('A B C'.split())
s2

0    A
1    B
2    C
dtype: object

## 범위를 시리즈의 value 생성한느데 사용하기 
    * range() / np.arange() 사용  같은 정수 범위지만 데이터 타입이 다름

In [15]:
s1 = pd.Series(range(10,14))
s1

0    10
1    11
2    12
3    13
dtype: int64

In [19]:
s = pd.Series(np.arange(200))
s

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

## 결측값 포함해서 시리즈
    * 결측값 NaN-numpy 라는 모듈에서 생성
    * 결측ㄱ밧 생성 위해서는 numpy 모듈 import


In [21]:
# nan 포함
s = pd.Series([1,2,3,np.nan,6,8])
s

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

## 인덱스 명시해서 시리즈 만들기 
* 숫자 인덱스 지정
    * s = pd.Series([1,2,3,],index = [1,2,3])

In [29]:
# 숫자
s1 = pd.Series([10,20,30,],index = [1,2,3])
s1

1    10
2    20
3    30
dtype: int64

In [30]:
# 문자 인덱스 지정
s2 = pd.Series([95,100,88],index = ['홍길','어쩔','성충향'])
s2


홍길      95
어쩔     100
성충향     88
dtype: int64

## 인덱스 활용

In [31]:
# 시리즈.index
s1.index

Int64Index([1, 2, 3], dtype='int64')

In [32]:
s2.index

Index(['홍길', '어쩔', '성충향'], dtype='object')

In [33]:
s= pd.Series([9904312, 3448737, 289045, 2466052],
            index=["서울","부산","인천","대구"])
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

## 시리즈 index.name 속성
    * 시리즈의 인덱스에 이름 붙이기 가능

In [34]:
s.index.name
s

서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [35]:
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

* 시리즈 값 

In [37]:
# 시리즈 값
s.values

array([9904312, 3448737,  289045, 2466052], dtype=int64)

##  시리즈.name 속성

In [38]:
# 시리즈 네임 속성 출력
print(s.name)

None


In [41]:
# 시리즈 네임 변경
s.name = '인구수'
s

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구수, dtype: int64

In [42]:
# 정수형 인덱스 접근
s[0]

9904312

In [44]:
# 문자열 인덱스 접근
s['서울']


9904312

In [46]:
# 둘다 
s[2],s['대구']

(289045, 2466052)

## 리스트 이용 인덱싱

In [47]:
# 여러개 접근
s[[1,2]]

도시
부산    3448737
인천     289045
Name: 인구수, dtype: int64

In [49]:
s[['서울','대구']]

도시
서울    9904312
대구    2466052
Name: 인구수, dtype: int64

## 문자 인덱스를 이용한 인덱싱
* .연산자를 이용해 접근가능: 객체명.문자인덱스명 

In [51]:
s.서울

9904312

In [54]:
s1 = pd.Series(range(3),index = ['a','b','c'])
s1

a    0
b    1
c    2
dtype: int64

In [55]:
s1.a

0

## 시리즈 슬라이싱(slicing)
* 정수형 위치 인덱스를 사용한 슬라이승
    * 시리즈[start:stop+1]  해야 stop까지 나옴
* 문자형 위치 슬라이스
    * 시리즈[start:end] :표시된 라벨 범위 모두 

In [56]:
# 값 2개 추출
s[1:3]

도시
부산    3448737
인천     289045
Name: 인구수, dtype: int64

In [57]:
# 문자 인덱스를 이용한 슬라이싱
# 2~4번째 값(3개값)
s['부산':'대구']

도시
부산    3448737
인천     289045
대구    2466052
Name: 인구수, dtype: int64

## 인덱스를 통한 시리즈 데이터 업데이트

In [58]:
s

도시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구수, dtype: int64

In [59]:
# '서울'변경
s['서울'] = 1000000   # s.서울 = 100000
s

도시
서울    1000000
부산    3448737
인천     289045
대구    2466052
Name: 인구수, dtype: int64

## 인덱스 재사용

In [60]:
s1 = pd.Series(np.arange(4),s.index)
s1

도시
서울    0
부산    1
인천    2
대구    3
dtype: int32

## 시리즈 연산

In [61]:
# 시리즈와 스칼라의 합
pd.Series([1,2,3])+4

0    5
1    6
2    7
dtype: int64

In [62]:
# 시리즈의 값을 1/10000 로 변경
s/1000000
#s 시리즈의 모든 value에 대하여 각각 연산을 진행

도시
서울    1.000000
부산    3.448737
인천    0.289045
대구    2.466052
Name: 인구수, dtype: float64

벡터화 인덱싱

In [65]:
#(s > 2500000) & (s< 5000000)
(s > 25e5) & (s< 50e5)  # e5 0 5ro
# s[(s > 2500000) & (s< 5000000)]


도시
서울    False
부산     True
인천    False
대구    False
Name: 인구수, dtype: bool

In [64]:
s0 = pd.Series(np.arange(10),np.arange(10)+1)
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [66]:
# 5보다 큰가
s0 > 5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [71]:
# 5보다 큰 요소 추출
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int32

In [73]:
# 짝수 호출
s0[s0%2==0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [74]:
# 인덱스가 5보다 큰거
s0.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
s0[s0>5]   ## ????

7     6
8     7
9     8
10    9
dtype: int32

In [76]:
# 값이 5보다 크고 8보다 작은 요소 추출
s0[(s0>5) & (s0<8)]

7    6
8    7
dtype: int32

In [78]:
# 값이 7이상인 수들의 합
s0[s0>= 7].sum() 

24

In [80]:
# 조건이 True 인 것들의 갯수
(s0>= 7).sum()

3

## 두시리즈간의 연산

In [83]:
num_s1 = pd.Series([1,2,3,4],index= ['a','b','c','d'])
num_s1

a    1
b    2
c    3
d    4
dtype: int64

In [82]:
num_s2 = pd.Series([5,6,7,8], index = ['b','c','d','a'])
num_s2

b    5
c    6
d    7
a    8
dtype: int64

* 시리즈간의 연산은 같은 인덱스를 찾아 연산을 진행
* 동일한 인덱스는 연산을 진행하고 나머지 인덱스는 연산처리가 불가해 nan값 처리

* 시리즈 + 시리즈 
    * 같은 인덱스를 찾아 + 수행

In [84]:
# 두 시리즈에 대한 + 연산
num_s1 + num_s2

a     9
b     7
c     9
d    11
dtype: int64

In [85]:
num_s3 = pd.Series([5,6,7,8], index = ['e','b','f','g'])
num_s4 = pd.Series([1,2,3,4], index = ['a','b','c','d'])

In [86]:
# 두 시리즈에 대한 + 연산
num_s3 + num_s4

a    NaN
b    8.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [87]:
# 두시리즈의 - 연산
num_s3 - num_s4

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [88]:
# 두시리즈 values 들간의 - 연산 
num_s3.values - num_s4.values

array([4, 4, 4, 4], dtype=int64)

In [89]:
a = num_s3.values
a

array([5, 6, 7, 8], dtype=int64)

# in 연산자 / for 반복문 사용
* 시리즈 객체는 라벨에 의해 인덱싱 가능
* 실질적으로는 라벨을 key로 가지는 딕셔너리와 같음
* 딕셔너리에서 제공하는 대부분의 연산자 사용가능
    * in 연산자: T/F
    * for 루프를 통해 각 원소의 key와 values에 접근

In [90]:
s

도시
서울    1000000
부산    3448737
인천     289045
대구    2466052
Name: 인구수, dtype: int64

In [91]:
# 인덱스 확인
'서울'in s

True

In [92]:
'울산' in s

False

In [93]:
'대전' not in s

True

In [95]:
# 딕셔너리의 item() 과 같은 함수가 시리즈에도 있음
s.items() # zip 객체

In [96]:
# list로 변환 후 확인
list(s.items())

[('서울', 1000000), ('부산', 3448737), ('인천', 289045), ('대구', 2466052)]

In [97]:
# 시리즈 각 원소 출력
for k,v in s.items():
    print(f'{k} = {v}')

서울 = 1000000
부산 = 3448737
인천 = 289045
대구 = 2466052


## 딕셔너리로 만들기

In [171]:
scores = {'홍길':96,'이몽':100,'성충':88}
s = pd.Series(scores)
s

홍길     96
이몽    100
성충     88
dtype: int64

In [100]:
city= pd.Series([9904312, 3448737, 289045, 2466052],
            index=["서울","부산","인천","대구"])
s = pd.Series(city)
s

서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

### 딕셔너리 기반으로 생성한 시리즈 인덱스 설정
* 딕셔너리의 원소는 순서를 갖지 않는다 
    * 딕셔너리 생성 시리즈 원소도 순서가 보장되지 않는다
    * 만약 순서를 보장하고싶으면 인덱스를 리스트로 지정한다

In [106]:
# 딕셔너리기반 생성한 시리즈 인덱스 설정
s = pd.Series(city,index = ["서울","부산","인천","대구"])
s

서울    9904312.0
부산          NaN
인천     289045.0
대구    2466052.0
dtype: float64

In [116]:
s['부산'] = 1630000
s

서울    9904312.0
인천     289045.0
대구    1875000.0
부산    1630000.0
dtype: float64

In [117]:
# 데이터 삭제 
del s['부산']
s

서울    9904312.0
인천     289045.0
대구    1875000.0
dtype: float64

In [118]:
# 새로운 값 추가
s['부산'] = 1875000
s

서울    9904312.0
인천     289045.0
대구    1875000.0
부산    1875000.0
dtype: float64

# Series 함수   ->  몇개 빼먹긴함
- size : 시리즈 원소 개수 반환
- shape : 튜플형태로 shape 반환
- unique(): 유일한 값만 ndarray로 반환
- count() : NaN을 제외한 개수를 반환
- mean() : NaN을 제외한 평균 
- value_counts() : NaN을 제외하고 각 값들의 빈도를 반환 

In [132]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])

In [133]:
s1.size


16

In [141]:
s1.shape

(16,)

In [134]:
len(s1)

16

* unique()
* count()  -> nan은 제외

- **unique()** : 시리즈의 유일한 값 반환

In [135]:
s1.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

**count()** : NaN을 제외한 개수를 반환

In [136]:
s1.count()


15

**mean()** : 데이터의 평균

In [137]:
# mean() 데이터 평균  결측치를 제외하고 구함
s1.mean()

2.6666666666666665

In [138]:
# numpy 의 1차원 데이터 생성하고 평균을 계산
a = np.array([2,2,2,2,np.NaN])   
a.mean()


nan

In [139]:
# 시리즈의 경우 평균은 nan을 제외하고 계산
b = pd.Series(a)  # numpy 데이터를 시리즈로 변경
b.mean()   # nan 빼고 계산

2.0

- **value_counts()** : 그룹핑된 원소별 개수 

In [140]:
# 각 원소들의 그룹별 빈도개수를 셈  (매핑?)
s1.value_counts()

1.0    5
2.0    4
3.0    2
5.0    2
7.0    1
4.0    1
dtype: int64

# 날짜 인덱스를 이용하여 시리즈 생성

In [ ]:
# 날짜 인덱스를 이용하여 시리즈 만들기
# 날짜표기 '년-월-일' 형태의 문자열로 표시


## 날짜 생성 함수 data_range()
* 판다스 패키지의 data_range함수(날짜생성)
pd.data_range(start=None,end=None,periods=None,freq='D)
*(시작날짜,끝날짜,날짜 생성기간,날짜 생성주기 ,기존값은 'D'(Day))
    * 끝날짜나 , 날짜 생성기간중 하나 필수 , 시작날짜는 필수 

## 243P

In [144]:
date = pd.date_range(start='2021-10-01',end= '2021-10-20')
date

DatetimeIndex(['2021-10-01', '2021-10-02', '2021-10-03', '2021-10-04',
               '2021-10-05', '2021-10-06', '2021-10-07', '2021-10-08',
               '2021-10-09', '2021-10-10', '2021-10-11', '2021-10-12',
               '2021-10-13', '2021-10-14', '2021-10-15', '2021-10-16',
               '2021-10-17', '2021-10-18', '2021-10-19', '2021-10-20'],
              dtype='datetime64[ns]', freq='D')

In [145]:
type(date)

pandas.core.indexes.datetimes.DatetimeIndex

In [151]:
# g3일간격 주기로 1001 에서 1020 으로
pd.date_range(start='2021-10-01',end= '2021-10-20',freq = '3D')

DatetimeIndex(['2021-10-01', '2021-10-04', '2021-10-07', '2021-10-10',
               '2021-10-13', '2021-10-16', '2021-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [155]:
# 1일 기준으로 1주일씩 증가하는 4개의 1주 시작일(일요일)
# 01은 금요일
pd.date_range(start='2021-10-01',end= '2021-10-20',freq = 'W')

DatetimeIndex(['2021-10-03', '2021-10-10', '2021-10-17'], dtype='datetime64[ns]', freq='W-SUN')

In [156]:
# 위와 같은결과
pd.date_range(start='2021-10-01',end= '2021-10-20',freq = 'W-SUN')

DatetimeIndex(['2021-10-03', '2021-10-10', '2021-10-17'], dtype='datetime64[ns]', freq='W-SUN')

In [157]:
# 월요일 기준
pd.date_range(start='2021-10-01',end= '2021-10-20',freq = 'W-MON')

DatetimeIndex(['2021-10-04', '2021-10-11', '2021-10-18'], dtype='datetime64[ns]', freq='W-MON')

In [158]:
# 금요일 기준
pd.date_range(start='2021-10-01',end= '2021-10-20',freq = 'W-FRI')

DatetimeIndex(['2021-10-01', '2021-10-08', '2021-10-15'], dtype='datetime64[ns]', freq='W-FRI')

In [160]:
# 7일 기준으로 1주일씩 증가하는 4개의 1주 시작일 (월요일)
# 7일 이후 부터 월요일 4개  periods 는 주기임
pd.date_range(start='2021-10-07',periods=4,freq = 'W-MON')

DatetimeIndex(['2021-10-11', '2021-10-18', '2021-10-25', '2021-11-01'], dtype='datetime64[ns]', freq='W-MON')

In [161]:
# 01일 기준으로 한달 간격의 일자4개 생성 : 월말기준
pd.date_range(start='2021-10-01',periods=4,freq = 'M')

DatetimeIndex(['2021-10-31', '2021-11-30', '2021-12-31', '2022-01-31'], dtype='datetime64[ns]', freq='M')

In [162]:
# 월초 기준
pd.date_range(start='2021-10-01',periods=4,freq = 'MS')

DatetimeIndex(['2021-10-01', '2021-11-01', '2021-12-01', '2022-01-01'], dtype='datetime64[ns]', freq='MS')

In [163]:
# 01일 기준으로 세달 간격의 일자4개 생성 : 월말기준
pd.date_range(start='2021-10-01',periods=4,freq = 'M')

DatetimeIndex(['2021-10-01', '2021-11-01', '2021-12-01', '2022-01-01'], dtype='datetime64[ns]', freq='MS')

In [164]:
# 2개우러 월초주기로 12개의 월말 날짜 생성
pd.date_range(start='2021-10-01',periods=12,freq = '2MS')

DatetimeIndex(['2021-10-01', '2021-12-01', '2022-02-01', '2022-04-01',
               '2022-06-01', '2022-08-01', '2022-10-01', '2022-12-01',
               '2023-02-01', '2023-04-01', '2023-06-01', '2023-08-01'],
              dtype='datetime64[ns]', freq='2MS')

In [165]:
# 분기시작일 기준 4개의 분기 시작일 생성
pd.date_range(start='2021-10-01',periods=4,freq = 'QS')

DatetimeIndex(['2021-10-01', '2022-01-01', '2022-04-01', '2022-07-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [166]:
# 20일 기준 연초
pd.date_range(start='2022-10-20',periods=4,freq = 'AS')

DatetimeIndex(['2023-01-01', '2024-01-01', '2025-01-01', '2026-01-01'], dtype='datetime64[ns]', freq='AS-JAN')

In [167]:
# 22-01-07 08:00 부터 시간 기준으로 10개의 날짜 생성
pd.date_range(start='2022-10-07 08:00',periods=10,freq = 'H')

DatetimeIndex(['2022-10-07 08:00:00', '2022-10-07 09:00:00',
               '2022-10-07 10:00:00', '2022-10-07 11:00:00',
               '2022-10-07 12:00:00', '2022-10-07 13:00:00',
               '2022-10-07 14:00:00', '2022-10-07 15:00:00',
               '2022-10-07 16:00:00', '2022-10-07 17:00:00'],
              dtype='datetime64[ns]', freq='H')

In [168]:
# 업무시간 기준 9 TO 5 로 설정되어있음 
pd.date_range(start='2022-10-07 08:00',periods=10,freq = 'BH')

DatetimeIndex(['2022-10-07 09:00:00', '2022-10-07 10:00:00',
               '2022-10-07 11:00:00', '2022-10-07 12:00:00',
               '2022-10-07 13:00:00', '2022-10-07 14:00:00',
               '2022-10-07 15:00:00', '2022-10-07 16:00:00',
               '2022-10-10 09:00:00', '2022-10-10 10:00:00'],
              dtype='datetime64[ns]', freq='BH')

In [169]:
# 30분 단위 가능
pd.date_range(start='2022-10-07 08:00',periods=10,freq = '30min')

DatetimeIndex(['2022-10-07 08:00:00', '2022-10-07 08:30:00',
               '2022-10-07 09:00:00', '2022-10-07 09:30:00',
               '2022-10-07 10:00:00', '2022-10-07 10:30:00',
               '2022-10-07 11:00:00', '2022-10-07 11:30:00',
               '2022-10-07 12:00:00', '2022-10-07 12:30:00'],
              dtype='datetime64[ns]', freq='30T')

In [170]:
# 10 초 단위
pd.date_range(start='2022-10-07 08:00',periods=10,freq = '10s')

DatetimeIndex(['2022-10-07 08:00:00', '2022-10-07 08:00:10',
               '2022-10-07 08:00:20', '2022-10-07 08:00:30',
               '2022-10-07 08:00:40', '2022-10-07 08:00:50',
               '2022-10-07 08:01:00', '2022-10-07 08:01:10',
               '2022-10-07 08:01:20', '2022-10-07 08:01:30'],
              dtype='datetime64[ns]', freq='10S')

#  Series 끝