numpy 임포트 -> 주피터는 기본으로 넘파이를 가지고있어 다운이 불필요
numpy.org -> 공식 홈페이지

In [1]:
import numpy as np

In [3]:
np.__version__

'1.20.1'

# Array 정의 및 사용
* 리스트 튜플 시퀸스 데이터 가져옴 -> 그냥 배열
* 형식 : arr_obj = np.array(seq_data)

In [5]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [6]:
data2 = [1,2,3,3.5,5]
data2

[1, 2, 3, 3.5, 5]

In [15]:
# 리스트 객체를 이용하여 array 생성
arr1 = np.array(data1)
arr1

array([1, 2, 3])

In [9]:
# array 크기확인
arr1.shape

(3,)

In [14]:
# 리스트 직접 입력하여 array 생성
arr2 = np.array([1,2,3,4,5])
arr2
# arr2.shape

array([1, 2, 3, 4, 5])

In [16]:
# array 자료형 확인 
arr2.dtype

dtype('int32')

In [17]:
arr3 = np.array([1,2,3,4.4,5])   #  -> array 변환시 전부 실수로 변경됨 np를 사용해서 이렇게됨
arr3

array([1. , 2. , 3. , 4.4, 5. ])

In [18]:
arr3.dtype

dtype('float64')

In [22]:
arr3.shape

(5,)

In [19]:
arr4 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr4.shape

(3, 3)

In [21]:
arr4.dtype

dtype('int32')

# 범위를 지정해 배열 생성(1) : np.arange() 함수
## 형식 : arr_obj =  np.arange([start,]stop[,step])

In [23]:
np.arange(10)   # -> array 형태의 range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
np.arange(1,10,2)    # -> 파이썬 이라 기본 문법은 비슷하다(같다?)

array([1, 3, 5, 7, 9])

### 내용.reshape(2,2) -> 1차원을 2행2열로 만듬

In [27]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
b1 = np.arange(12).reshape(3,4)
b1.shape

(3, 4)

In [31]:
b2 = np.arange(7).reshape(3,3)  # -> 행렬로 바꾸려는 원소 객수가 일치해야함 인덱스에러와 비슷

ValueError: cannot reshape array of size 7 into shape (3,3)

In [33]:
b3 = b1.reshape(4,3)   # -> 원소 갯수만 맞다면 어떤 행열 로 바꿔도 상관없음
b3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# 범위를 지정해 배열 생성(2) linspace() 함수
## 형식 arr_obj = np.linspace(start,stop[, nu. = 50]) 기본이 50값

### arange  는 정수값 
### linspace 는실수라고 생각

In [34]:
np.linspace(1,10,10)    # (시작,끝,나타낼범위) 1부터 10까지 10개를 나타냄 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
np.linspace(0,np.pi)

array([0.        , 0.06411414, 0.12822827, 0.19234241, 0.25645654,
       0.32057068, 0.38468481, 0.44879895, 0.51291309, 0.57702722,
       0.64114136, 0.70525549, 0.76936963, 0.83348377, 0.8975979 ,
       0.96171204, 1.02582617, 1.08994031, 1.15405444, 1.21816858,
       1.28228272, 1.34639685, 1.41051099, 1.47462512, 1.53873926,
       1.60285339, 1.66696753, 1.73108167, 1.7951958 , 1.85930994,
       1.92342407, 1.98753821, 2.05165235, 2.11576648, 2.17988062,
       2.24399475, 2.30810889, 2.37222302, 2.43633716, 2.5004513 ,
       2.56456543, 2.62867957, 2.6927937 , 2.75690784, 2.82102197,
       2.88513611, 2.94925025, 3.01336438, 3.07747852, 3.14159265])

In [40]:
np.linspace(1,10).shape

(50,)

# 특별한 형태의 배열생성
## np.zeros(), np.ones(), np.eye()
### 모든 요소가 0인 배열 생성
### 디폴트는 실수인 float

In [42]:
np.zeros(10,dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.zeros((3,5)).reshape(5,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 모든 요소가 1인 배열

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 대각요소가 1인 배열생성

In [48]:
# 3으로 하면 3행 3열의 대각요소가 1인 배열 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.eye(3,4)  # -> 기본값은 float

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [51]:
np.eye(4,3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [52]:
np.eye(3,4,k =2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [53]:
np.eye(3,4,k =1 , dtype = int)  # -> k는 하나씩 밀어줌

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [55]:
np.eye(3,4,k = -1 , dtype = int)  # -> k = 1은 오른쪽 -1 은 왼쪽

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

## 정방행렬  대각 요소가 1
### 대각요소만 1인것을 단위 행렬
### 단위 행렬 생성 np.identity(n,dtype = 자료형)

In [56]:
# n*n 크기위 단위행렬 생성
np.identity(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## 초기화 되지 않은 배열 생성 : np.empty(shape,dtype = float)

In [57]:
# 초기화 되지 않은 배열 생성
np.empty(4)

array([4.18767318e-062, 1.47915151e-071, 1.04917089e-142, 2.38195485e+190])

## 배열의 데이터 타입 변환 astype()
### num_arr = str_srr.astype(dtype)
#### dtype = int, float, str

In [58]:
np.array(['1.5','0.62','2','3.14','3.142345'])

array(['1.5', '0.62', '2', '3.14', '3.142345'], dtype='<U8')

In [70]:
str_a1 = np.array(['1.5','0.62','2','3.14','3.142345'])  # 문자열이라도 실수가 있으면 float로 해줘야함
num_a1 = str_a1.astype('float32')
num_a1 = str_a1.astype(float)      # 위처럼 하면 float32 비트 가 나옴
num_a1

array([1.5     , 0.62    , 2.      , 3.14    , 3.142345])

In [66]:
str_a1.dtype

dtype('<U8')

In [68]:
num_a1.dtype

dtype('float64')

In [75]:
str_a2 = np.array(['1','3','5','6','8'])   
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 6, 8])

In [76]:
num_a3 = str_a2.astype(int)
num_a3

array([1, 3, 5, 6, 8])

## 실수형 배열을 정수형 배여롤 변환
### 아예 정수로 반환 

In [78]:
num_f1 = np.array([10,21,0.549,4.75,5.89])
num_f1

array([10.   , 21.   ,  0.549,  4.75 ,  5.89 ])

In [84]:
num_i1 = num_f1.astype(int)    # 문자가 아니라 숫자라서 가능한듯
num_i1

array([10, 21,  0,  4,  5])

In [82]:
num_f1.dtype

dtype('float64')

In [83]:
num_i1.dtype

dtype('int32')

## 숫자형 배열을 문자열  배열로 변환

In [85]:
num_f1.astype('U')   # 유니코드

array(['10.0', '21.0', '0.549', '4.75', '5.89'], dtype='<U32')

In [87]:
num_f1.astype('S') # 'S' 혹은 'a' 바이트코드 문자열

array([b'10.0', b'21.0', b'0.549', b'4.75', b'5.89'], dtype='|S32')

## 난수 배열생성
### random.rand() , random.randint()

In [89]:
np.random.rand(10)  # 0과 1사이에 실수값 10개   실수난수
# np.random.rand(2,5)  # 2행 5열로만듬

array([0.84250209, 0.44576694, 0.92564852, 0.86587356, 0.92989609,
       0.31308562, 0.92640276, 0.40430635, 0.95978265, 0.59893315])

In [90]:
np.random.rand()  # 하나만 생성

0.6678201476625372

In [91]:
np.random.rand(2,3,4)  # (개,행,열)

array([[[0.97291925, 0.06639545, 0.95126457, 0.88719055],
        [0.12278218, 0.61412349, 0.02750863, 0.65267114],
        [0.83696446, 0.78009692, 0.80976764, 0.70610222]],

       [[0.60336953, 0.79904717, 0.53376266, 0.69886713],
        [0.45622018, 0.56383518, 0.32405775, 0.5268533 ],
        [0.69716546, 0.24736261, 0.19045126, 0.65765338]]])

In [98]:
np.random.randint(10)   # 정수난수  1~10 사이에 하나

8

In [100]:
np.random.randint(10,20)

14

In [101]:
np.random.randint(10,20,size=(3,5))   # 10 에서 20사이에 3행5열

array([[15, 11, 14, 17, 14],
       [10, 15, 17, 14, 15],
       [14, 16, 11, 16, 10]])

# Array 연산
## 기본연산 (합,차,곱,나눗셈 등)
### 기본적으로  동일한 크기의 array간 연산 수행

In [107]:
arr1 = np.array([[1,2,3,],[4,3,6]])
arr1

array([[1, 2, 3],
       [4, 3, 6]])

In [105]:
arr2 = np.array([[10, 11, 12], [13, 14, 15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [109]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(10,16).reshape(2,3)
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [111]:
print(arr1.shape,arr2.shape)

(2, 3) (2, 3)


## 배열의 연산

In [112]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [113]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [114]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [115]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [116]:
arr2 * 2

array([[20, 22, 24],
       [26, 28, 30]])

In [118]:
arr2 > 12

array([[False, False, False],
       [ True,  True,  True]])

## bordcasting 크기가 다른 배열 연산

In [119]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [121]:
(arr1.shape,arr3.shape)

((2, 3), (3,))

In [122]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [123]:
arr1 **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

## 브로드 캐스트 조건 
http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html
